doc: update README.md
prisma/pulse-railway-pg-config pull request #6
Opened 2024-03-19 12:59 UTC by ankur-arch

2024-03-27 16:09 UTC, grpatel reviewed
looks good to me!

2024-03-28 09:39 UTC, nikolasburk requested changes

2024-03-28 09:39 UTC, nikolasburk commented on README.md
> +1. Follow the [guide](https://pris.ly/railway-template-setup-docs) to set up Prisma Pulse using the Railway template.
anchor is broken, needs to link to: `#setup-with-template-prisma-pulse-db-only`

2024-03-28 10:37 UTC, nikolasburk approved these changes

2024-03-28 10:37 UTC, nikolasburk approved these changes

2024-03-28 13:02 UTC, merged